=== Axway/ats-framework/agent/agentapp/systemoperations/src/main/resources/META-INF/agent_descriptor.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="component">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="actionClass" minOccurs="1" maxOccurs="unbounded">
                
                    <xs:annotation>
                        <xs:documentation xml:lang="en">
                            Action class element
                        </xs:documentation>
                    </xs:annotation>
                    
                    <xs:complexType>
                    
                        <xs:attribute name="name" type="classPath" use="required">
                            <xs:annotation>
                                <xs:documentation xml:lang="en">
                                    Action class full
                                    name.
                                    e.g. org.axway.component.SomeActionClass
                                </xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        
                        <xs:attribute name="initializeRequestUrl" type="URL" use="optional">
                            <xs:annotation>
                                <xs:documentation xml:lang="en">
                                    Relative ( to the ATS agent REST API location ) URL 
                                    for creating instance of this Action class on the agent.
                                    For internal use only. Do not use it for your own custom actions.
                                    e.g. processes/executor
                                </xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        
                    </xs:complexType>
                    
                </xs:element>

                <xs:element name="initHandler" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="name" type="classPath" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="finalHandler" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="name" type="classPath" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="cleanupHandler" minOccurs="1"
                    maxOccurs="1">
                    <xs:complexType>
                        <xs:attribute name="name" type="classPath" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element ref="environment" minOccurs="0" maxOccurs="unbounded" />

            </xs:sequence>
            <xs:attribute name="name" type="notEmptyString" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="environment">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="database" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="file" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="directory" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="name" type="notEmptyString" use="optional" />
            <xs:attribute name="backupFolder" type="notEmptyString"
                use="optional">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Backup folder path for
                        Unix based systems.
                        If not specified - the system temp directory
                        will be used.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="windowsBackupFolder" type="notEmptyString"
                use="optional">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Backup folder path for
                        Windows system.
                        If not specified - the system temp directory will
                        be used.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="table" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="host" type="notEmptyString" use="optional" />
            <xs:attribute name="port" type="xs:positiveInteger" use="optional" />
            <xs:attribute name="user" type="notEmptyString" use="required" />
            <xs:attribute name="password" type="notEmptyString" use="required" />
            <xs:attribute name="name" type="notEmptyString" use="optional" />
            <xs:attribute name="type" type="dbType" use="required">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Database type: oracle,
                        mysql, ...
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="sid" type="notEmptyString" use="optional" />
            <xs:attribute name="serviceName" type="notEmptyString"
                use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="dbType">
        <xs:restriction base="notEmptyString">
            <xs:enumeration value="oracle" />
            <xs:enumeration value="mysql" />
            <xs:enumeration value="mssql" />
            <xs:enumeration value="cassandra" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="table">
        <xs:complexType>
            <xs:attribute name="name" type="notEmptyString" use="required" />
            <xs:attribute name="columnsToExclude" type="notEmptyString"
                use="optional">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Column names (comma
                        separated) to exclude from backup.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="lock" type="xs:boolean" use="optional"
                default="true">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Indicates if the table
                        will be locked during restore.
                        Default value is 'true'.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="autoIncrementResetValue" type="xs:nonNegativeInteger"
                use="optional">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Reset value for Auto
                        increment columns or Sequences.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="file">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="action" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="path" type="notEmptyString" use="required" />
            <xs:attribute name="backupName" type="notEmptyString"
                use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:element name="directory">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="action" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="path" type="notEmptyString" use="required" />
            <xs:attribute name="backupName" type="notEmptyString"
                use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="notEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="action">
        <xs:complexType>
            <xs:attribute name="command" type="notEmptyString" use="required" />
            <xs:attribute name="sleep" type="xs:nonNegativeInteger" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="classPath">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9\\.\\_\\-]+" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="URL">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9//-]+" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Axway/ats-framework/agent/core/src/test/resources/agent_descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="agenttest" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./agent_descriptor.xsd">
	
    <actionClass name="com.axway.ats.agent.core.ant.component.agenttest.FirstActionClass"/>
    <actionClass name="com.axway.ats.agent.core.ant.component.agenttest.SecondActionClass"/>
    <actionClass name="com.axway.ats.agent.core.ant.component.agenttest.WrongActionClass"/>
    
    <actionClass name="com.axway.ats.agent.core.ant.needed_in_acgen_tests.ActionClassWithConstants"/>
    
    <actionClass name="com.axway.ats.agent.core.ant.needed_in_acgen_tests.TestWithReturnValuesClass"/>
    <actionClass name="com.axway.ats.agent.core.ant.needed_in_acgen_tests.TestWithInputValuesClass"/>
    
    <actionClass name="com.axway.ats.agent.core.ant.needed_in_acgen_tests.ComplexActionClass"/>
    
    <actionClass name="com.axway.ats.agent.core.ant.needed_in_acgen_tests.test.TestWithMemberClasses"/>
    <actionClass name="com.axway.ats.agent.core.ant.needed_in_acgen_tests.test.FirstMemberClass"/>
    <actionClass name="com.axway.ats.agent.core.ant.needed_in_acgen_tests.test.memberclasses.SecondMemberClass"/>
    
    <initHandler name="com.axway.ats.agent.core.ant.component.agenttest.InitHandler"/>
    <finalHandler name="com.axway.ats.agent.core.ant.component.agenttest.FinalHandler"/>
    <cleanupHandler name="com.axway.ats.agent.core.ant.component.agenttest.CleanupHandler"/>
</component>

=== Axway/ats-framework/agent/core/src/test/resources/test_descriptors/test_agent_descriptor_windows_backup_folder.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="agenttest" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../src/agent_descriptor.xsd">
	
    <actionClass name="com.axway.ats.agent.core.ant.component.agenttest.FirstActionClass"/>
    
    <initHandler name="com.axway.ats.agent.core.ant.component.agenttest.InitHandler"/>
    
    <finalHandler name="com.axway.ats.agent.core.ant.component.agenttest.FinalHandler"/>
    
    <cleanupHandler name="com.axway.ats.agent.core.ant.component.agenttest.CleanupHandler"/>
    
    <environment windowsBackupFolder="C:/agent_backup_dir" >

         <file path="C:/test.txt" backupName="backup_test.txt" />
         
         <directory path="C:/agent_orig/original dir/" backupName="backup dir" />
         
         <directory path="C:/agent_orig_2/original dir2/" />
         
    </environment>

</component>

=== Axway/ats-framework/agent/core/src/test/resources/com/axway/ats/agent/core/descriptor_oracle.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="dlpautomation" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../src/agent_descriptor.xsd">
	
    <!--All the action classes are defined below-->
    <actionClass name="com.axway.mft.dlp.automation.fixtures.action.PackageProcessorTool"/>
   
    <!--Initialization handler-->
    <initHandler name="com.axway.mft.dlp.automation.fixtures.InitHandler"/>
    
    <!--Custom cleanup handler-->
    <cleanupHandler name="com.axway.mft.dlp.automation.fixtures.CleanupHandler"/>
    
    <!--Environment description-->
    <environment backupFolder="/var/corvigo">
    
        <!--Oracle tables--> 
        <database name="mft" user="axway" password="axway" type="oracle" sid="some_sid">
        
            <table name="SETTINGS"/>
        
            <!-- policy tables -->
            <table name="POLICIES" columnsToExclude="LAST_UPDATE"/>
	        <table name="POLICY_ANNOTATIONS" columnsToExclude="LAST_UPDATE"/>
	        <table name="POLICY_ANNOTATIONS_PER_LOCALE"/>
	        <table name="POLICY_ATTACHMENT_LISTS"/>
	        <table name="POLICY_INBOUND_ORDER" columnsToExclude="LAST_UPDATE"/>
	        <table name="POLICY_LDAP_GROUP"/>
	        <table name="POLICY_LDAP_QUERY"/>
	        <table name="POLICY_NAME_LIST" />
	        <table name="POLICY_NOTIFICATIONS" columnsToExclude="LAST_UPDATE"/>
	        <table name="POLICY_NOTIF_PER_LOCALE"/>
	        <table name="POLICY_OUTBOUND_ORDER" columnsToExclude="LAST_UPDATE"/>
	        <table name="POLICY_PROPERTIES"/>
	        <table name="POLICY_SHARED_LIST_ATTRIBUTE"/>
	        <table name="POLICY_SHARED_LIST_SOURCE"/>
	        <table name="POLICY_SHARED_LIST_UPD_STATUS"/>
	        <table name="POLICY_SHARED_LISTS"/>
	        <table name="POLICY_TAG_USAGE" />
	        <table name="POLICY_TAGS" columnsToExclude="LAST_UPDATE"/>
	        <table name="POLICY_WORD_LISTS" />
	        
            <!-- package store tables (FIXME: should be handled by PS Agent component) -->
            <table name="PACKAGESTOREPKGVIEWUSER"/>
            <table name="PACKAGESTOREPKGVIEWREF"/>
            <table name="PACKAGESTOREPKGVIEW"/>
            <table name="PACKAGESTOREPKGUSER"/>
            <table name="PACKAGESTOREPKG"/>
            <table name="PACKAGESTORESTREAMREF"/>
            <table name="PACKAGESTORESTREAMCHUNK"/>
            <table name="PACKAGESTORESTREAM"/>

            <!-- package tags -->
            <table name="POLICYPACKAGETAGLOG"/>
            
            <!-- queue processor -->
            <table name="PACKAGE_PROCESSOR_QUEUE"/>

            <!-- user tables -->
            <table name="LOCAL_USER"/>
            <table name="USER_PASSWORDS"/>
            
            <!-- RBAC tables -->
            <table name="ROLE_ASSIGNMENTS"/>
            <table name="IDENTITIES"/>
            
            <!-- Package logging tables -->
            <table name="MFTPACKAGESTREAMLOG"/>
            <table name="MFTPACKAGETRACKINGLOG"/>
            <table name="MFTPACKAGEUSERLOG"/>
            <table name="MFTPACKAGELOG"/>
        
            <!-- MCS tables -->
            <table name="MCSMAILRECIPIENT"/>
            <table name="MCSMAILQUEUE"/>
        </database>
        
        <file path="testfile1.txt"/>
        <file path="testfile2.txt" backupName="testfile2.txt_backup"/>
    </environment>
</component>

=== Axway/ats-framework/agent/core/src/test/resources/test_descriptors/test_agent_descriptor_with_more_env_same_env_names.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="agenttest"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../src/agent_descriptor.xsd">

    <actionClass name="com.axway.ats.agent.core.ant.component.agenttest.FirstActionClass"/>

    <cleanupHandler name="com.axway.ats.agent.core.ant.component.agenttest.CleanupHandler"/>

    <!-- Environment 1 -->
    <environment name="env" backupFolder="/var/backup/agent_backup" windowsBackupFolder="D:/test_tmp" >

        <file path="/tmp/test1.txt"/>

        <file path="/tmp/test2.txt">
            <action command="proc1" sleep="3"/>
        </file>

    </environment>


    <!-- Environment 2 -->
    <environment name="env" backupFolder="/var/backup/agent_backup_2" windowsBackupFolder="D:/test_tmp2">

        <directory path="C:/agent_orig_2/original dir2/" />

    </environment>

</component>

=== Axway/ats-framework/agent/core/src/test/resources/test_descriptors/test_agent_descriptor_with_more_env.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="agenttest"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../src/agent_descriptor.xsd">

    <actionClass name="com.axway.ats.agent.core.ant.component.agenttest.FirstActionClass"/>

    <cleanupHandler name="com.axway.ats.agent.core.ant.component.agenttest.CleanupHandler"/>

    <!-- Environment 1 -->
    <!--  Drive letter for widowsBackupFolder is changed from d:/test to c:/test
        as D: is CD/DVD-ROM on some machines and this exception is get on myDir.getCanonicalPath():
    Caused by: java.io.IOException: The device is not ready
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.Win32FileSystem.canonicalize(Win32FileSystem.java:396)
        at java.io.File.getCanonicalPath(File.java:559)
        at com.axway.ats.environment.file.DirectoryEnvironmentUnit.<init>(DirectoryEnvironmentUnit.java:55)
     -->
    <environment name="env1" backupFolder="/var/backup/agent_backup" windowsBackupFolder="C:/test_tmp" >

        <file path="/tmp/test1.txt"/>

        <file path="/tmp/test2.txt">
            <action command="proc1" sleep="3"/>
        </file>

    </environment>


    <!-- Environment 2 -->
    <environment name="env2" backupFolder="/var/backup/agent_backup_2" windowsBackupFolder="C:/test_tmp2">

        <directory path="C:/agent_orig_2/original dir2/" />

    </environment>

</component>

=== Axway/ats-framework/agent/core/src/test/resources/test_descriptors/test_agent_descriptor_with_additional_actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="agenttest" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../src/agent_descriptor.xsd">
	
    <actionClass name="com.axway.ats.agent.core.ant.component.agenttest.FirstActionClass"/>    
    <cleanupHandler name="com.axway.ats.agent.core.ant.component.agenttest.CleanupHandler"/>
    
    <environment backupFolder="/var/backup/agent_backup" >

	    <file path="/tmp/test1.txt"/>
	
		<file path="/tmp/test2.txt">
			<action command="proc1" sleep="3"/>
		</file>
	
		<file path="/tmp/test3.txt">
			<action command="proc1" sleep="5"/>
			<action command="proc2" sleep="0"/>
		</file>
	</environment>

</component>

=== Axway/ats-framework/agent/agentapp/systemoperations/src/main/resources/META-INF/agent_descriptor.xml
<?xml version='1.0' encoding='utf-8'?>
<component name="auto-system-operations"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="agent_descriptor.xsd">

	<actionClass
		name="com.axway.ats.agent.components.system.operations.InternalFileSystemOperations"
		initializeRequestUrl="filesystem" />
	<actionClass
		name="com.axway.ats.agent.components.system.operations.InternalFileSystemSnapshot"
		initializeRequestUrl="filesystem/snapshot" />
	<actionClass
		name="com.axway.ats.agent.components.system.operations.InternalSystemInputOperations"
		initializeRequestUrl="system/input" />
	<actionClass
		name="com.axway.ats.agent.components.system.operations.InternalSystemOperations"
		initializeRequestUrl="system" />
	<actionClass
		name="com.axway.ats.agent.components.system.operations.InternalProcessOperations"
		initializeRequestUrl="processes/executors" />
	<actionClass
		name="com.axway.ats.agent.components.system.operations.InternalProcessTalker"
		initializeRequestUrl="processes/talkers" />
	<actionClass
		name="com.axway.ats.agent.components.system.operations.InternalRegistryOperations"
		initializeRequestUrl="registry" />
	<actionClass
		name="com.axway.ats.agent.components.system.operations.MachineDescriptionOperations"
		initializeRequestUrl="machine/description" />

	<cleanupHandler
		name="com.axway.ats.agent.components.system.operations.CleanupHandler" />
</component>

=== Axway/ats-framework/agent/core/src/test/resources/com/axway/ats/agent/core/descriptor_with_port.xml
<?xml version="1.0" encoding="UTF-8"?>
<component name="stautomation" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../../src/agent_descriptor.xsd">
	
    <!--All the action classes are defined below-->
    <actionClass name="com.axway.st.automation.fixtures.configuration.accounts.subscription.SentToSettings"/>
    
    <!--Custom cleanup handler-->
    <cleanupHandler name="com.axway.st.automation.fixtures.CleanupHandler"/>

    <!--Environment description-->
    <environment backupFolder="/opt/TMWD/SecureTransport">
    
        <!--Oracle tables--> 
        <database host="127.127.127.127" port="33060" name="st" user="root" password="axway" type="mysql">
            <table name="AT_CustAttr_LocalCerts"/>
            <table name="AT_CustAttr_PartnerCerts"/>
            <table name="Account"/>
            <table name="Application"/>
            <table name="Application_BusinessUnit"/>
            <table name="BusinessUnit"/>
            <table name="CertificateKey"/>
            <table name="CertificateReference"/>
            <table name="CertificateRequest"/>
            <table name="CustomAttributes"/>
            <table name="CustomProperties"/>
            <table name="DataTransformation"/>
            <table name="DelegatedAdministrator"/>
            <table name="DelegatedAdministrator_BusinessUnit"/>
            <table name="Event"/>
            <table name="LicenseSubject"/>
            <table name="Revision"/>
            <table name="Site"/>
            <table name="SiteTemplate"/>
            <table name="Subscription"/>
            <table name="SubtransmissionStatus"/>
            <table name="TransferConfiguration"/>
            <table name="TransferData"/>
            <table name="TransferStatus"/>
            <table name="VirtualUser"/>
        </database>
        
        <file path="testfile1.txt"/>
        <file path="testfile2.txt" backupName="testfile2.txt_backup"/>
    </environment>
</component>
